# Sekand hend ataking.
secondhand_attack:
    type: world
    debug: false
    events:
        on player right clicks entity:
          - if <player.item_in_offhand.material.is[==].to[m@wooden_sword]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playeffect at:<player.location.forward.add[0,1.2,0]> effect:sweep_attack offset:0 visibility:2
                          - playsound at:<context.entity.location> sound:entity_player_attack_sweep volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - foreach <player.location.find.living_entities.within[1.5].exclude[<player>].exclude[<context.entity>]>:
                            - if <[value]> != null:
                              - hurt <[value]> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[2]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1




          - if <player.item_in_offhand.material.is[==].to[m@stone_sword]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playeffect at:<player.location.forward.add[0,1.2,0]> effect:sweep_attack offset:0 visibility:2
                          - playsound at:<context.entity.location> sound:entity_player_attack_sweep volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - foreach <player.location.find.living_entities.within[1.5].exclude[<player>].exclude[<context.entity>]>:
                            - if <[value]> != null:
                              - hurt <[value]> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[2]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1



          - if <player.item_in_offhand.material.is[==].to[m@golden_sword]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playeffect at:<player.location.forward.add[0,1.2,0]> effect:sweep_attack offset:0 visibility:2
                          - playsound at:<context.entity.location> sound:entity_player_attack_sweep volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - foreach <player.location.find.living_entities.within[1.5].exclude[<player>].exclude[<context.entity>]>:
                            - if <[value]> != null:
                              - hurt <[value]> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[2]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1



          - if <player.item_in_offhand.material.is[==].to[m@iron_sword]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playeffect at:<player.location.forward.add[0,1.2,0]> effect:sweep_attack offset:0 visibility:2
                          - playsound at:<context.entity.location> sound:entity_player_attack_sweep volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - foreach <player.location.find.living_entities.within[1.5].exclude[<player>].exclude[<context.entity>]>:
                            - if <[value]> != null:
                              - hurt <[value]> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[2]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1



          - if <player.item_in_offhand.material.is[==].to[m@diamond_sword]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playeffect at:<player.location.forward.add[0,1.2,0]> effect:sweep_attack offset:0 visibility:2
                          - playsound at:<context.entity.location> sound:entity_player_attack_sweep volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - foreach <player.location.find.living_entities.within[1.5].exclude[<player>].exclude[<context.entity>]>:
                            - if <[value]> != null:
                              - hurt <[value]> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[2]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1



          - if <player.item_in_offhand.material.is[==].to[m@netherite_sword]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playeffect at:<player.location.forward.add[0,1.2,0]> effect:sweep_attack offset:0 visibility:2
                          - playsound at:<context.entity.location> sound:entity_player_attack_sweep volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - foreach <player.location.find.living_entities.within[1.5].exclude[<player>].exclude[<context.entity>]>:
                            - if <[value]> != null:
                              - hurt <[value]> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[2]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1



          - if <player.item_in_offhand.material.is[==].to[m@wooden_axe]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playsound at:<context.entity.location> sound:entity_player_attack_strong volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1



          - if <player.item_in_offhand.material.is[==].to[m@stone_axe]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playsound at:<context.entity.location> sound:entity_player_attack_strong volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1



          - if <player.item_in_offhand.material.is[==].to[m@golden_axe]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playsound at:<context.entity.location> sound:entity_player_attack_strong volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1



          - if <player.item_in_offhand.material.is[==].to[m@iron_axe]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playsound at:<context.entity.location> sound:entity_player_attack_strong volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1



          - if <player.item_in_offhand.material.is[==].to[m@diamond_axe]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playsound at:<context.entity.location> sound:entity_player_attack_strong volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1



          - if <player.item_in_offhand.material.is[==].to[m@netherite_axe]>:
            - if <player.item_in_offhand.has_lore>:
              - if <player.has_flag[sechand_atk_cd]> = false:
                - if <player.is_sneaking> = false:
                  - if <context.entity> != null:
                    - if <player.worldguard.test_flag[pvp]> = true || <player.location.in_region> = false:
                      - determine passively cancelled
                      - flag <player> sechand_atk_cd expire:<script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_speed].mul[-1].div[2]>
                      - if <player.is_sprinting> = true:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - push <context.entity> origin:<context.entity.location> destination:<player.location.forward[7].add[0,3,0]> no_rotate speed:0.4
                          - playsound <context.entity.location> sound:entity_player_attack_knockback pitch:1 volume:1
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - if <player.is_on_ground> = false:
                        - define loc1 <player.location.y>
                        - wait 1t
                        - define loc2 <player.location.y>
                        - if <[loc2]> < <[loc1]>:
                          - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                          - if <context.entity.gamemode.is[!=].to[creative]||false>:
                            - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage]> source:<player> cause:ENTITY_ATTACK
                            - playsound <context.entity.location> sound:entity_player_attack_crit pitch:1 volume:1
                            - playeffect <context.entity.location.add[0,1,0]> effect:crit quantity:20 offset:0.3 velocity:0.1
                            - if <player.gamemode.is[!=].to[creative]||false>:
                              - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                          - else:
                            - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1
                      - else:
                        - animate <player> animation:ARM_SWING_OFFHAND for:<server.online_players>
                        - if <context.entity.gamemode.is[!=].to[creative]||false>:
                          - playsound at:<context.entity.location> sound:entity_player_attack_strong volume:1 pitch:1
                          - hurt <context.entity> <script[<player.item_in_offhand.script.name>].data_key[data.stats.attribute_modifiers.generic_attack_damage].div[1.5]> source:<player> cause:ENTITY_ATTACK
                          - if <player.gamemode.is[!=].to[creative]||false>:
                            - inventory adjust slot:offhand durability<player.item_in_offhand.durability.sub[1]>
                        - else:
                          - playsound at:<context.entity.location> sound:entity_player_attack_weak volume:1 pitch:1